### ISSUE TITLE
Can the usage of webots in the example be more specific, and can it work on Windows

### ISSUE THREAD

**Issue by wangning1234** [SpesRobotics/teleop#2]

**Comment by lukicdarkoo** [comment]
@wangning1234 We haven't explicitly tested Webote + teleop, but it should work. Webots works under Webots and teleop is CI tested on Windows.

Do you face any specific issues?

**Comment by wangning1234** [comment]
maybe my device didn‘t support webots，I am planning to try it in my another computer with ubuntu,i will let you know how it work.

**Comment by lukicdarkoo** [comment]
@wangning1234 On Windows, instead of `webots worlds/teleop.wbt` you should be able to open the simulation with double-click or inside Webots `File > Open World...`

**Comment by wangning1234** [comment]
I did it this way before, but it didn't work. Maybe there was a problem with my Python environment configuration
